[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for static export - handle clean URLs
[[redirects]]
  from = "/about"
  to = "/about/"
  status = 200

[[redirects]]
  from = "/deals"
  to = "/deals/"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login/"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup/"
  status = 200

[[redirects]]
  from = "/wishlist"
  to = "/wishlist/"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy/"
  status = 200

[[redirects]]
  from = "/disclosure"
  to = "/disclosure/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Allow external images from Amazon CDN
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://m.media-amazon.com https://images-na.ssl-images-amazon.com https://images.amazon.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self';"
